name: Build Cross Platform Executables

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Build for ${{ matrix.os }}/${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ linux, windows, darwin ]
        arch: [ amd64, arm64 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.19.13'

      - name: Build executable
        env:
          CGO_ENABLED: 0
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          GOEXE: ${{ matrix.os == 'windows' && '.exe' || '' }}
        run: |
          mkdir -p dist
          go build -o dist/arbiter-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }} \
            -ldflags="-s -w" \
            ./cmd/arbiter
          if [ "${{ matrix.os }}" != "windows" ]; then
            chmod +x dist/arbiter-${{ matrix.os }}-${{ matrix.arch }}
          fi

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/arbiter-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
